/*
	WARNING!
	This file was autogenerated by StablexUI-Designer.
	
	Don't change it manually, because it's can do unstable the work of StablexUI-Designer
		and can damage your project.
*/

package %InstancePackage%;

@:noCompletion class Suid {
	public static function getCurrSeconds () : Int // workaround for https://github.com/RealyUniqueName/StablexUI/issues/235
		return Date.now().getHours() * 60 * 60 + Date.now().getMinutes() * 60 + Date.now().getSeconds();
	
	public static function castType <T> (v:Dynamic, c:Class<T>) : T // needed for ViewStack
		return Std.is(v, c) ? cast v : null;
	
	public static function getCwd () : String
		return Suid.escPath(Sys.getCwd());
	
	public static function fullPath (path:String) : String
		return Suid.escPath(sys.FileSystem.fullPath(path));
	
	public static function escPath (path:String) : String // workaround for Windows
		return StringTools.replace(path, "\\", "/");
	
	public static function getSettings (guiName:String) : Dynamic {
		return switch (guiName) {
			// switchers of guiSettings
			default: null;
		}
	}
}

class %InstanceName% {
	@:noCompletion macro public static function geInit () : Void {
		ru.stablex.ui.UIBuilder.regClass("%InstancePackageDot%Suid");
		ru.stablex.ui.UIBuilder.regClass("haxe.io.Path");
		ru.stablex.ui.UIBuilder.regClass("ru.stablex.ui.skins.Skin");
		ru.stablex.ui.UIBuilder.regClass("openfl.display.BitmapData");
		
		// build sources from xml
	}
	
	#if !macro
	// fields of instances
	
	public static function load () : Void {
		// UIBuilder initialization
		
		// skins registration
		
		// initialization of instances
	}
	#end
}
