/*
	WARNING!
	This file was autogenerated by StablexUI-Designer.
	
	Don't change it manually, because it's can do unstable the work of StablexUI-Designer
		and can damage your project.
*/

package %InstancePackage%;

class %InstanceName% {
	@:noCompletion macro public static function geInit () : Void // create source of GuiElements class
	
	#if !macro
	// instance fields
	
	public static function load () {
		ru.stablex.ui.UIBuilder.regClass("haxe.io.Path");
		ru.stablex.ui.UIBuilder.regClass("openfl.display.BitmapData");
		ru.stablex.ui.UIBuilder.regClass("ru.stablex.ui.skins.Skin");
		
		// UIBUilder initialization + RTXml
		
		// skins registration
		
		// instance initialization
	}
	#end
}
